#!/bin/sh

. config/.env.gild.lib

echo "↓確認"
echo $MASTER_PUSH_CONTROL
echo "↑確認"

if [ $MASTER_PUSH_CONTROL ] && [ $MASTER_PUSH_CONTROL = no ]; then
    return
fi

while read local_ref local_sha remote_ref remote_sha
do
    # masterへのpush禁止
    if [[ "${remote_ref##refs/heads/}" = "master" ]]; then
        echo $'\e[1;31morigin/masterへはpushできません。\e[0m'
        exit 1
    fi
done

exit 0
